
package by.epam.persistance.bean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JaxwsControllerService", targetNamespace = "http://controller.epam.by/", wsdlLocation = "http://localhost:8070/common_war_exploded/JaxwsTicket?wsdl")
public class JaxwsControllerService
    extends Service
{

    private final static URL JAXWSCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException JAXWSCONTROLLERSERVICE_EXCEPTION;
    private final static QName JAXWSCONTROLLERSERVICE_QNAME = new QName("http://controller.epam.by/", "JaxwsControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8070/common_war_exploded/JaxwsTicket?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JAXWSCONTROLLERSERVICE_WSDL_LOCATION = url;
        JAXWSCONTROLLERSERVICE_EXCEPTION = e;
    }

    public JaxwsControllerService() {
        super(__getWsdlLocation(), JAXWSCONTROLLERSERVICE_QNAME);
    }

    public JaxwsControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSCONTROLLERSERVICE_QNAME, features);
    }

    public JaxwsControllerService(URL wsdlLocation) {
        super(wsdlLocation, JAXWSCONTROLLERSERVICE_QNAME);
    }

    public JaxwsControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSCONTROLLERSERVICE_QNAME, features);
    }

    public JaxwsControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JaxwsController
     */
    @WebEndpoint(name = "JaxwsControllerPort")
    public JaxwsController getJaxwsControllerPort() {
        return super.getPort(new QName("http://controller.epam.by/", "JaxwsControllerPort"), JaxwsController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JaxwsController
     */
    @WebEndpoint(name = "JaxwsControllerPort")
    public JaxwsController getJaxwsControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.epam.by/", "JaxwsControllerPort"), JaxwsController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSCONTROLLERSERVICE_EXCEPTION!= null) {
            throw JAXWSCONTROLLERSERVICE_EXCEPTION;
        }
        return JAXWSCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
